Save synced filenams and skip sync next times
yihong0618/running_page pull request #454
Opened 2023-07-18 10:12 UTC by agassiyzh

GPX 文件解析很快。但是fit是二进制的，解析比较慢。

这个PR记录了同步过的数据文件，在后面的同步中跳过这个文件。

2023-07-18 10:33 UTC, yihong0618 commented
@ben-29 can you help to review this~ thanks

2023-07-18 11:02 UTC, yihong0618 commented on scripts/generator/__init__.py
> +import utils
from utils import save_synced_data_file_list

2023-07-18 11:02 UTC, yihong0618 commented on scripts/gpxtrackposter/track_loader.py
> +import utils
ditto

2023-07-18 11:04 UTC, agassiyzh commented
生成svg的时候有问题。我再改改

2023-07-18 11:08 UTC, yihong0618 commented
@agassiyzh 邀请你作为协作者了～

2023-07-18 15:38 UTC, ben-29 commented
> @ben-29 can you help to review this~ thanks

ok, will do it tomorrow~

2023-07-19 14:40 UTC, ben-29 requested changes
It's better to cache .fit files for better performance, great work!

2023-07-19 14:40 UTC, ben-29 commented on scripts/utils.py
> +from config import SYNCED_FILE_NAME
This file can be kept unchanged.

2023-07-20 10:55 UTC, yihong0618 approved these changes

2023-07-20 10:56 UTC, yihong0618 commented
@agassiyzh nice work thanks

2023-07-20 15:08 UTC, ben-29 reviewed
There is one final task remaining. In order to maintain code consistency, you can replace `SYNCED_FILE_NAME` with the absolute path `SYNCED_FILE`.

2023-07-22 17:00 UTC, ben-29 reviewed
@agassiyzh After my test, I noticed that if the Fit files were already synced before applying this patch, their file names would not be added to the `SYNCED_FILE` list. Could you please make a small adjustment?

2023-07-22 17:00 UTC, ben-29 commented on scripts/config.py
> +SYNCED_FILE = os.path.join(parent, "imported.json")
Where do you want to save `SYNCED_FILE`? Maybe use `FIT_FOLDER` instead of `parent`?

2023-07-22 17:00 UTC, ben-29 commented on scripts/generator/__init__.py
> +                synced_files.extend(t.file_names)
What if the record already synced before this patch, would the `file_name` be saved in `SYNCED_FILE`?

2023-07-22 17:00 UTC, ben-29 commented on scripts/generator/__init__.py
> +                synced_files.extend(t.file_names)
ditto

2023-07-22 17:00 UTC, ben-29 commented on scripts/utils.py
> +import os
Don't forget to revert this file.

2023-07-23 01:39 UTC, ben-29 approved these changes
Well Done, Thank you!

2023-07-23 01:41 UTC, merged

2023-07-23 03:24 UTC, ben-29 commented
This pr causes one problem, there is no `file_names` when `sync_from_app` , fix in #463